name: modulo11
description: Lib Module11.
version: 0.0.1
repository: https://github.com/arivanjuniordev/modulo11

# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

#dependencies:
  #coverage: 1.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
